### ISSUE TITLE
inputnamelists for files that appear with 'unkown_' or 'same_as' should not appear in the pop

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/POP2-CESM#23]
### Description of the issue:
the pop.input_data_list should not have entries for filenames that start with 'unknown_' or 'same_as'
since these are not on disk and the latest version of cime will not recognize them. Special logic should not be in cime to ignore these (as was the case before). These fixes need to be made in pop.

### Version:
- CESM: [version]
- POP2: [version]

**Comment by alperaltuntas** [comment]
I am testing a fix. Will follow up with a pr.

**Comment by mvertens** [comment]
Thank you so much for your quick response!
